# Generated by Django 6.0.1 on 2026-01-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriski_broj', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('vremetraenje', models.PositiveIntegerField()),
                ('fotografija', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.CharField(choices=[('D', 'dostapen'), ('R', 'rezeriran'), ('S', 'servis')], max_length=1)),
                ('tip', models.CharField(choices=[('K', 'kinematski'), ('F', 'fvp'), ('I', 'industtriski')], max_length=1)),
                ('kompanija', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('br_rezervacii', models.PositiveIntegerField()),
                ('isActive', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('termin', models.CharField(choices=[('U', 'utro'), ('P', 'popladne'), ('V', 'vecer')], max_length=1)),
                ('zabeleshka', models.TextField()),
                ('kod', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('C', 'cekanje'), ('A', 'aktivna'), ('Z', 'zavrshena')], max_length=1)),
                ('dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DronoviApp.dron')),
                ('odgovoren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DronoviApp.pilot')),
            ],
            options={
                'unique_together': {('dron', 'datum', 'termin')},
            },
        ),
        migrations.CreateModel(
            name='PilotRezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DronoviApp.pilot')),
                ('rezervacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DronoviApp.rezervacija')),
            ],
        ),
    ]
