# Generated by Django 5.2.5 on 2025-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_authorlog_book_pages_book_size_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
