# Generated by Django 5.2.6 on 2025-09-04 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='baker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
