# Generated by Django 6.0.1 on 2026-01-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_published', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('isReserved', models.BooleanField(default=False)),
                ('isSold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=50)),
                ('profile_url', models.CharField(max_length=50)),
                ('total_sales', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NedvizninaApp.characteristic')),
                ('real_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NedvizninaApp.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NedvizninaApp.agent')),
                ('real_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NedvizninaApp.realestate')),
            ],
        ),
    ]
