# Generated by Django 6.0.1 on 2026-01-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NedvizninaApp', '0002_rename_real_state_agentrealestate_real_estate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
    ]
