# Generated by Django 6.0.1 on 2026-01-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NedvizninaApp', '0004_agent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristicrealestate',
            old_name='real_state',
            new_name='real_estate',
        ),
    ]
