# Generated by Django 5.2.5 on 2025-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(blank=True, max_length=50, null=True)),
                ('imeNaProizveduvac', models.CharField(blank=True, max_length=50, null=True)),
                ('maxPatnici', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50, null=True)),
                ('prezime', models.CharField(blank=True, max_length=50, null=True)),
                ('godinaNaRagjanje', models.CharField(blank=True, max_length=50, null=True)),
                ('vkupnoCasoviNaLet', models.IntegerField(blank=True, null=True)),
                ('cinVoKompanijata', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
