# Generated by Django 5.2.5 on 2025-08-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvioKompanija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50, null=True)),
                ('godinaNaOsnovanje', models.IntegerField(blank=True, null=True)),
                ('LetanadvorOdEvropa', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvioKompanijaPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviokompanija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotApp.aviokompanija')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Let',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sifra', models.CharField(blank=True, max_length=50, null=True)),
                ('aerodromPoletuva', models.CharField(blank=True, max_length=50, null=True)),
                ('aerodromSletuva', models.CharField(blank=True, max_length=50, null=True)),
                ('fotografija', models.ImageField(blank=True, null=True, upload_to='flights/')),
                ('aviokompanija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotApp.aviokompanija')),
                ('balon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotApp.ballon')),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotApp.pilot')),
            ],
        ),
    ]
